### ISSUE TITLE
AWS 서베이

### ISSUE THREAD

**Issue by muzholiq** [mundajung/lit-hub#1]
### 이슈 요약
- 로깅 시스템 구축을 위한 서베이
- 아마도 AWS 사용할 것 같은데, 사용해본 적이 없어 서베이가 필요함

**Comment by muzholiq** [comment]
@mundajung 님 프로젝트 오너 등록 부탁드립니더 😄 
이슈 어사인이 안됨 ㅋㅋㅋㅋㅋㅋㅋ

**Comment by muzholiq** [comment]
https://aws.amazon.com/ko/getting-started/

**Comment by muzholiq** [comment]
@mundajung 생각해보니 로깅 시스템 쌩으로 새로 하려면 Kafka, storm 다 구축해야하네요 ㅌㅌㅌㅌ amazon solution 쓰는게ㅜ나을듯 ?

**Comment by mundajung** [comment]
@muzholiq 그러나 처음부터 하면, 일이니.. 적당한 선에서 끊고 가는 것도 나쁘지 않지요!

**Comment by muzholiq** [comment]
### 상황 공유
- AWS tutorial(wordpress)
  - https://aws.amazon.com/ko/getting-started/tutorials/launch-a-wordpress-website/

**Comment by muzholiq** [comment]
### 로깅 시스템 관련
- `Amazon CloudWatch`라는 솔루션 사용 예정
  - 기존 시스템, 애플리케이션 및 커스텀 로그 파일을 사용하는 시스템과 애플리케이션을 모니터링하고 문제를 해결할 수 있습니다.
  - EC2와 연동 가능하고, 특정 구문, 값 또는 패턴(지표)에 대한 로그를 거의 실시간으로 모니터링 가능하다고 합니다.
  - access log는 간단히(?) `CloudWatch` 사용해서 연동 가능해 보입니다.
  - 더 나아가서, 프론트 노출 log는 별도의 api가 필요해 보입니다.
    - @mundajung 님 해당 작업 요청드려도 괜찮을까요 ? 
      - access log 이용하여 `CloudWatch`에서 한번에 분석하는 것이 좋을 것 같습니다.
      - (사실 해당 작업은 추후에 진행해도 될 것 같네요.. 어짜피 page access log로 capacity 를 정하는거라 현재 상황에서 굳이 필요할까 싶습니다.)
      - endpage에서 api를 호출하여 남겨지는 access log를 활용하려고 합니다.
      - main page의 경우, access log로 가능할 것 같네요( position 정보를 남길 수 있으려나요 ?)
      - album end page의 경우, 어떤 플랫폼 클릭이 발생했는지 정도 남겨주시면 좋을 것 같습니다.


### AWS 배포 관련
-  `AWS S3` 에 build한 jar upload후 , `EC2`로 빌드하는 task로 진행하면 될 것 같습니다.
  - `EC2`는 그냥 장비 한대 라고 생각하시면 될 듯 합니다. 지금 레벨에서는 load balancing 등 고도화된 task는 필요없을 것 같네요.
  - 추후 필요하다면 `elastic beanstalk` 등 다른 솔루션들도 있습니다. (물론 과금이 .. ㅋㅋ) 
  - @mundajung 님 참고 부탁드려요~

**Comment by muzholiq** [comment]
### AWS mySQL 연동 가이드
- http://blog.saltfactory.net/how-to-start-mysql-on-aws/

**Comment by mundajung** [comment]
This issue was moved to lit-hub/server#1
