### ISSUE TITLE
repo private 전환

### ISSUE THREAD

**Issue by muzholiq** [mundajung/lit-hub#13]
### 방법
- https://help.github.com/articles/making-a-public-repository-private/
- @mundajung 님 ..저에게는 repo 화면에서 setting이 뜨지 않숩니다 😭

**Comment by muzholiq** [comment]
### team repo를 새로 파자 ! 
- https://github.com/account/organizations/new

**Comment by muzholiq** [comment]
https://github.com/lit-hub 
생성 완료
@mundajung @mirumi10 님 초대됫는지 확인 부탁드려요~

**Comment by muzholiq** [comment]
https://github.com/lit-hub/lithub-backend 로 이관이 필요합니다

**Comment by mundajung** [comment]
This issue was moved to lit-hub/server#13
