### ISSUE TITLE
Domain survey

### ISSUE THREAD

**Issue by muzholiq** [mundajung/lit-hub#2]
### 상황 공유
- 구매 가능한 도메인을 확인해보자
-new gTLD 중심으로?

**Comment by muzholiq** [comment]
### 참고자료
- https://domaintyper.com/domain-names/top-level-domains/new-gTLD
- 해외 기준 new gTLD
  - `.tunes`도 졸업되면
 - 국내에서 구매 가능한지 확인 필요

**Comment by muzholiq** [comment]
가비아 포함 몇개 찾아보았는데 tunes는 국내 호스팅 업체들은 관심도 없는듯 ㅋㅋㅋ 
lithub.io 기즌 연 20만원…
.com 은 연 2만원입니더

**Comment by mundajung** [comment]
`lit.hub` 가능여부

**Comment by muzholiq** [comment]
- `lithub.lol` 로 구매 진행 예정
  - [도메인 견적서.pdf](https://github.com/mundajung/lit-hub/files/1701767/default.pdf)

**Comment by muzholiq** [comment]
### 참고
- AWS에서도 도메인 구매가 가능한듯 ?
  - https://aws.amazon.com/ko/getting-started/tutorials/get-a-domain/

**Comment by muzholiq** [comment]
### 상황 공유
- AWS domain 구매는 가능하나 ..  `.lol`은 제공하지 않는다 ..
- AWS wordpress 성공
  - elastic ip : 35.169.216.80

**Comment by muzholiq** [comment]
### 상황 공유
- domain 결제하고 AWS 연결해보려고 했더니 ... macOS에서는 결제가 안된다네 ..? 😭 
<img width="1015" alt="2018-02-07 10 36 52" src="https://user-images.githubusercontent.com/16659029/35919130-7e9d650e-0c57-11e8-890b-54697e594f1b.png">

**Comment by mundajung** [comment]
This issue was moved to lit-hub/server#2
