### ISSUE TITLE
Data Sample Kit

### ISSUE THREAD

**Issue by mundajung** [mundajung/lit-hub#5]
데이터 샘플 포맷: [lit-hub_data.xlsx](https://github.com/mundajung/lit-hub/files/1688061/lit-hub_data.xlsx)
- 1차 버전에서 100명 샘플링
- 이미지는 bugsmusic 에서 받기
- music platform 별 url은 mobile을 우선으로 따기
  - 멜론, 네이버는 pc 일 경우 알아서 redirect.
  - 지니는 pc 버전만 존재.
  - 엠넷은 자동 rediect 지원 X.

**Comment by mundajung** [comment]
- 2018/02/06 1차 정리본: [lit-hub_data_v1.xlsx](https://github.com/mundajung/lit-hub/files/1706301/lit-hub_data_v1.xlsx)
  - url pc to mobile 전환 @mundajung
  - 이미지검수 @mirumi10 
  - 인스타그램 대표 url 선정작업 @mirumi10 
  - 고유 album path 작업 @muzholiq

**Comment by muzholiq** [comment]
@mundajung album path 작업 찬우님께 요청드렸습니다~

**Comment by mundajung** [comment]
This issue was moved to lit-hub/server#5
